### PR TITLE
mysqli support for my-movies application

### PR DESCRIPTION
**Pull request by utdrmac**

### CODE REVIEW

**Comment by grypyrg** [comment]
As I haven't used this exercise in years, I can't really approve/disapprove this PR. Feel free to merge whenever you want :-)

**Comment by utdrmac** [comment]
Oh you should have been using it! We had a blast with it today! Everyone was so engaged, working, joking, bouncing ideas around, etc. Had a clear winning team and they won $25 each to some local brewery.

**Comment by grypyrg** [comment]
I really need to see how you approach it, maybe that can convince me. Do you have a full outline on how to setup and do it?

**Comment by utdrmac** [comment]
I've got some commits coming that add it to ansible for easy setup and there is a slide module that I can clean up a bit more. Scoreboard setup is done via ansible now too so that's easy.

**Comment by grypyrg** [comment]
👍

**Pull request merged**
